//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SertifiTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SertifiTests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;Name&quot;:&quot;Jack&quot;,&quot;StartYear&quot;:2013,&quot;EndYear&quot;:2016,&quot;GPARecord&quot;:[3.4,2.1,1.2,3.6]},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;Jill&quot;,&quot;StartYear&quot;:2010,&quot;EndYear&quot;:2013,&quot;GPARecord&quot;:[3.3,2.3,1.1,3.7]},{&quot;Id&quot;:3,&quot;Name&quot;:&quot;Bob&quot;,&quot;StartYear&quot;:2010,&quot;EndYear&quot;:2012,&quot;GPARecord&quot;:[2.3,2.5,2.8]},{&quot;Id&quot;:4,&quot;Name&quot;:&quot;Alice&quot;,&quot;StartYear&quot;:2013,&quot;EndYear&quot;:2016,&quot;GPARecord&quot;:[3.6,2.9,3.4,3.7]},{&quot;Id&quot;:5,&quot;Name&quot;:&quot;Eve&quot;,&quot;StartYear&quot;:2012,&quot;EndYear&quot;:2015,&quot;GPARecord&quot;:[3.3,2.5,1.1,3.7]},{&quot;Id&quot;:6,&quot;Name&quot;:&quot;Malcom&quot;,&quot;StartYear&quot;:2011,&quot;EndYear&quot;:2014,&quot;GPARecord&quot;:[3.8,2.7,1.1,3.7]},{&quot;Id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;Name&quot;:&quot;Jack&quot;,&quot;StartYear&quot;:2013,&quot;EndYear&quot;:2016,&quot;GPARecord&quot;:[3.4,2.1,1.2,3.6]},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;Jill&quot;,&quot;StartYear&quot;:2010,&quot;EndYear&quot;:2013,&quot;GPARecord&quot;:[3.3,2.3,1.1,3.7]},{&quot;Id&quot;:3,&quot;Name&quot;:&quot;Bob&quot;,&quot;StartYear&quot;:2010,&quot;EndYear&quot;:2012,&quot;GPARecord&quot;:[2.3,2.5,2.8]},{&quot;Id&quot;:4,&quot;Name&quot;:&quot;Alice&quot;,&quot;StartYear&quot;:2013,&quot;EndYear&quot;:2016,&quot;GPARecord&quot;:[3.6,2.9,3.4,3.7]},{&quot;Id&quot;:5,&quot;Name&quot;:&quot;Eve&quot;,&quot;StartYear&quot;:2012,&quot;EndYear&quot;:2015,&quot;GPARecord&quot;:[3.3,2.5,1.1,3.7]},{&quot;Id&quot;:6,&quot;Name&quot;:&quot;Malcom&quot;,&quot;StartYear&quot;:2011,&quot;EndYear&quot;:2014,&quot;GPARecord&quot;:[3.8,2.7,1.1,3.7]},{&quot;Id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StudentsEqualTest {
            get {
                return ResourceManager.GetString("StudentsEqualTest", resourceCulture);
            }
        }
    }
}
